//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedEgresados.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex_Alumnos
    {
        public int Rol { get; set; }
        public string Sexo { get; set; }
        public Nullable<System.DateTime> Fecha_nac { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> Ano_Egreso { get; set; }
        public string Cargo { get; set; }
        public string Descripcion_Cargo { get; set; }
        public string Empresa { get; set; }
    
        public virtual Personas Personas { get; set; }
    }
}
