//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedEgresados.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personas
    {
        public int Rol { get; set; }
        public string Nombres { get; set; }
        public string Apellido_Paterno { get; set; }
        public string Apellido_Materno { get; set; }
        public int Estado { get; set; }
    
        public virtual Ex_Alumnos Ex_Alumnos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
