//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedEgresados.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int Rol { get; set; }
        public string Correo { get; set; }
        public string Password { get; set; }
        public int Estado { get; set; }
        public int TipoUsuario { get; set; }
    
        public virtual Personas Personas { get; set; }
        public virtual Tipos Tipos { get; set; }
    }
}
